### ISSUE TITLE
Problem 1188 in the Planning Domains API points to a domain file `m10-strips.pddl`

### ISSUE THREAD

**Issue by ztangent** [AI-Planning/classical-domains#16]
This was brought to my attention due to failing tests in Julia package I maintain, which provides access to the planning.domains repository: https://github.com/JuliaPlanners/PlanningDomains.jl/issues/4

When you make a request to the JSON API for problem 1188, this is what is returned:

```
{
  "error": false,
  "result": {
    "average_effective_width": null,
    "average_effective_width_description": " ",
    "domain": "elevators",
    "domain_id": 37,
    "domain_path": "classical/elevators-00-adl/domain.pddl",
    "domain_url": "https://www.haz.ca/planning-domains/classical/elevators-00-adl/domain.pddl",
    "hplus": null,
    "hplus_description": " ",
    "lower_bound": null,
    "lower_bound_description": " ",
    "max_effective_width": null,
    "max_effective_width_description": " ",
    "problem": "m10-strips.pddl",
    "problem_id": 1188,
    "problem_path": "classical/elevators-00-adl/m10-strips.pddl",
    "problem_url": "https://www.haz.ca/planning-domains/classical/elevators-00-adl/m10-strips.pddl",
    "tags": "[\":conditional-effects\",\":negative-preconditions\",\":typing\"]",
    "upper_bound": null,
    "upper_bound_description": " "
  }
}
```

However, if you go to the URL (https://www.haz.ca/planning-domains/classical/elevators-00-adl/m10-strips.pddl), the file is a domain file, rather than a problem file.

I'm not exactly sure if this is an API issue or a file issue or both, but I figured I'd flag it here!

**Comment by haz** [comment]
Thanks! Definitely a file issue. Not sure where that m10-strips file even came from, to be honest. Domain is nearly a quarter of a century old, so it'd be hard to trace down :P.

I'll soon remove the DB entry entirely, and do let me know if any other issues pop up.

**Comment by haz** [comment]
Should be all set...thanks, again!
